name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js for Linting
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies and Lint Backend
        working-directory: ./backend
        run: |
          npm ci
          npm run lint

      - name: Install Dependencies and Lint Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: lint-and-build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Backend Version from package.json
        id: backend-version
        working-directory: ./backend
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=$version" >> $GITHUB_ENV

      - name: Extract Frontend Version from package.json
        id: frontend-version
        working-directory: ./frontend
        run: |
          version=$(node -p "require('./package.json').version")
          echo "version=$version" >> $GITHUB_ENV

      - name: Log In to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_LOGIN }}
          password: ${{ secrets.GHCR_SECRET }}

      - name: Build and Push Backend Image
        working-directory: ./backend
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_LOGIN }}/devops-backend:${{ env.version }} .
          docker push ghcr.io/${{ secrets.GHCR_LOGIN }}/devops-backend:${{ env.version }}

      - name: Build and Push Frontend Image
        working-directory: ./frontend
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_LOGIN }}/devops-frontend:${{ env.version }} .
          docker push ghcr.io/${{ secrets.GHCR_LOGIN }}/devops-frontend:${{ env.version }}